main: com.tndt.PluginMain
name: bukkit-groovy
version: 1.0
author: Adam Kis (aregic@gmail.com)
description: Run groovy scripts from paper
api-version: 1.18
commands:
  gx:
    description: Execute a groovy script
    usage: /gx
    permission: minecraft.command.debug
    permission-message: You don't have the minecraft.command.debug permission.
  gxall:
    description: Reload all groovy scripts
    usage: /gxall
    permission: minecraft.command.debug
    permission-message: You don't have the minecraft.command.debug permission.
  gxunloadall:
    description: Unload all groovy scripts
    usage: /gxunloadall
    permission: minecraft.command.debug
    permission-message: You don't have the minecraft.command.debug permission.
  gxunload:
    description: Unload a groovy script
    usage: /gxunload
    permission: minecraft.command.debug
    permission-message: You don't have the minecraft.command.debug permission.